name: webclient
description: Web client for DigiSlides
# version: 1.0.0
#homepage: https://www.example.com
#author: Issac <email@example.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  nuts:
    path: ../../jaguar/nuts
  fontawesome:
    path: ../../jaguar/fontawesome
  bson_objectid: ^0.1.0
  path: 1.6.1

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
