name: webclient
description: Web client for DigiSlides
# version: 1.0.0
#homepage: https://www.example.com
#author: Issac <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  nuts:
    path: ../nuts
  #fontawesome:
  #  path: ../../jaguar/fontawesome
  # bson_objectid: ^0.1.0
  path:

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
